### ISSUE TITLE
Building in VS2015 Update 2

### ISSUE THREAD

**Issue by undecided2013** [weidazhao/Hosting#11]
I've ran into 2 issues building this in VS2015 Update 2. First, the projects would not load. The xproj was targeting dotnet instead of dnx. Changed to DNX and the projects loaded. Now I am getting compile errors across the board. Not sure what is wrong.
Errors like this: "Error    NU1002  The dependency System.Text.Encodings.Web 4.0.0-rc2-24008 in project Counter does not support framework .NETFramework,Version=v4.5.2.    Counter C:\development\Hosting-dotnetcli\Counter\project.json"

I have installed the latest DNX from here:
http://docs.asp.net/en/latest/getting-started/installing-on-windows.html

![hostingbuildproblems](https://cloud.githubusercontent.com/assets/5455854/14506899/18a81eae-018e-11e6-88e0-b96338cb816a.jpg)

**Comment by weidazhao** [comment]
Yes, in order to make it compile and run with DNX from within VS, I believe the code would require some change. The purpose of the DNX branch is simply for making the solution openable in VS 2015 Update 2. For now, please follow the steps in README.MD to build and run the sample. There is a script for building the code from command line, as well as PowerShell script for deploying the application.

**Comment by undecided2013** [comment]
That worked, thanks

**Comment by undecided2013** [comment]
OK, so everything built and deployed but the TestClient is not building. I do not see any binary artifacts from that project. How do I execute the TestClient?

Thx
