### ISSUE TITLE
Where is rc2 used?

### ISSUE THREAD

**Issue by senj** [weidazhao/Hosting#5]
Hello,

first, great work on this. This is exacly what I was waiting and looking for.

Is there a way to see which code requires the RC2 beta, because I can build the solution with RC1-update1 but it fails at runtime. I try to run only the Counter Service.

noob question: is it possible to run RC1 with the bits of RC2 I need to host this ?

Thanks..

**Comment by weidazhao** [comment]
Thanks for your feedback! All the code in this repo requires RC 2. You can check out project.json of the projects, where most of the NuGet package references have versions 1.0.0-rc2-*. There are lots of breaking changes in RC 2 since RC 1, so I don't think you will be able to run RC 1 and RC 2 bits together.
